import type { NextPage } from 'next'
import Head from "next/head";
import { dehydrate, useQuery } from "react-query";
import { getUserByName, getUsers, queryClient } from "../utils/api";

const Home: NextPage = ({ name }: any) => {
  const data = useQuery("getUsers", async () => await getUsers());
  return (
    <>
      {JSON.stringify(data.data)}
      <Head>
        <title>Ait Placements</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>hello</main>

      <footer></footer>
    </>
  );
};

export async function getServerSideProps() {
  await queryClient.prefetchQuery("getUsers", async () => await getUsers());
  return {
    props: {
      name: "sourabh",
      dehydratedState: dehydrate(queryClient),
    },
  };
}

export default Home
