import React, { useEffect, useState } from "react";
import PropTypes from "prop-types";
import Image from "next/image";
import aitlogo from "../assets/aitlogo.gif";
import Head from "next/head";
import Link from "next/link";
import { Box, Button, Grid, TextField, Typography } from "@mui/material";
import toast, { Toaster } from "react-hot-toast";
import { BACKEND_ROUTES, FRONTEND_ROUTES } from "./api/routes";
import { useRouter } from "next/router";
import { useAuth } from "../utils/useAuth";
import { useCookies } from "react-cookie";

function Login() {
  const [email, setEmail] = useState("");
  const [pass, setPass] = useState("");
  const router = useRouter();

  useEffect(() => {
    // router.push(FRONTEND_ROUTES.DASHBOARD);
    return () => {};
  }, []);

  async function sendLoginCred() {
    const loginapi = fetch(BACKEND_ROUTES.LOGIN, {
      method: "POST",
      body: JSON.stringify({
        email,
        pass,
      }),
    });
    const resp = await loginapi;
    const data = await resp.json();

    if (data.error) {
      toast.error(data.error);
    }
    if (data.message) {
      const now = new Date();
      toast.success(data.message);
      router.push(FRONTEND_ROUTES.DASHBOARD);
    }
  }
  return (
    <div>
      <Toaster />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Box
          display="flex"
          flexDirection="column"
          alignItems="center"
          justifyContent="center"
          height="100vh"
          margin={"auto"}
        >
          <a className="inline-block mb-6" href="#">
            <Image width={60} height={60} src={aitlogo} alt="" />
          </a>

          <Typography
            variant="h3"
            className="mb-4 text-2xl md:text-3xl font-bold"
          >
            Sign in to your account
          </Typography>
          <Grid
            container
            direction="column"
            spacing={2}
            justifyContent="center"
            sx={{ width: 400 }}
          >
            <Grid item>
              <TextField
                fullWidth
                required
                id="standard-required"
                label="Email"
                variant="filled"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
              />
            </Grid>

            <Grid item alignItems="center">
              <TextField
                fullWidth
                required
                id="standard-required"
                label="Password"
                variant="filled"
                value={pass}
                onChange={(e) => setPass(e.target.value)}
              />
            </Grid>
            <Grid item>
              <Button
                variant="contained"
                color="success"
                size="large"
                fullWidth
                onClick={sendLoginCred}
              >
                Login
              </Button>
            </Grid>

            <Grid item sx={{ cursor: "pointer" }}>
              <Box display="flex" justifyContent="space-between">
                <Box sx={{ textAlign: "left" }}>
                  Dont Have an Account?
                  <Link passHref href="/register">
                    <Typography
                      variant="body2"
                      sx={{ fontWeight: 700 }}
                      color="slateblue"
                    >
                      Register
                    </Typography>
                  </Link>
                </Box>
                <Box sx={{ textAlign: "right" }}>
                  Forgot Password?
                  <Link passHref href="/forgotpass">
                    <Typography
                      variant="body2"
                      sx={{ fontWeight: 700 }}
                      color="slateblue"
                    >
                      Recover
                    </Typography>
                  </Link>
                </Box>
              </Box>
            </Grid>
          </Grid>
        </Box>
      </main>

      <footer></footer>
    </div>
  );
}

export default Login;
