import { useState } from "react";
import Image from "next/image";
import aitlogo from "../assets/aitlogo.gif";
import Head from "next/head";
import Dropdown from "../components/dropdown";
import Link from "next/link";
import { NextPage } from "next";

const yearList: IDropdown[] = [
  { key: "First Year(FE)", value: "FE" },
  { key: "Second Year(SE)", value: "SE" },
  { key: "Third Year(TE)", value: "TE" },
  { key: "Final Year(BE)", value: "BE" },
  { key: "Master 2nd Year(ME)", value: "ME" },
];
const branchList: IDropdown[] = [
  { key: "Compouter Science(COMP)", value: "COMP" },
  { key: "Info Technology(IT)", value: "IT" },
  { key: "Electronics & Comm(EnTC)", value: "EnTC" },
  { key: "Mechanical(Mech)", value: "Mech" },
];

const Register: NextPage = () => {
  const [selectedYear, setselectedYear] = useState(yearList[0].key);
  const [selectedBranch, setselectedBranch] = useState(branchList[0].key);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className="flex h-full min-h-screen items-center justify-center w-full bg-white">
          <div className=" w-2/3 max-w-3xl my-10">
            <div className="mb-6 text-center">
              <a className="inline-block mb-6" href="#">
                <Image width={60} height={60} src={aitlogo} alt="" />
              </a>
              <h3 className="mb-4 text-2xl md:text-3xl font-bold">
                Register your account
              </h3>
            </div>
            <form action="">
              <div className="mb-6 grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label
                    className="block mb-2 text-coolGray-800 font-medium"
                    htmlFor=""
                  >
                    Name
                  </label>
                  <input
                    className="appearance-none block w-full p-3 leading-5 text-slate-900 border border-coolGray-200 rounded-lg shadow-md placeholder-coolGray-400 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-opacity-50"
                    type="text"
                    placeholder="Firstname Sirname"
                  />
                </div>
                <div>
                  <label
                    className="block mb-2 text-slate-800 font-medium"
                    htmlFor=""
                  >
                    Email
                  </label>
                  <input
                    className="appearance-none block w-full p-3 leading-5 text-slate-900 border border-coolGray-200 rounded-lg shadow-md placeholder-coolGray-400 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-opacity-50"
                    type="email"
                    placeholder="studentname_regno@aitpune.edu.in"
                  />
                </div>
              </div>
              <div className="mb-6 grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <Dropdown
                    buttonname="Year"
                    dropdown={yearList}
                    data={selectedYear}
                    setData={setselectedYear}
                  />
                </div>
                <div>
                  <Dropdown
                    buttonname="Branch"
                    dropdown={branchList}
                    data={selectedBranch}
                    setData={setselectedBranch}
                  />
                </div>
              </div>
              <div className="mb-6">
                <label
                  className="block mb-2 text-slate-800 font-medium"
                  htmlFor=""
                >
                  Registration Number
                </label>
                <input
                  className="appearance-none block w-full p-3 leading-5 text-slate-900 border border-coolGray-200 rounded-lg shadow-md placeholder-coolGray-400 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-opacity-50"
                  type="number"
                  placeholder="18XXX"
                />
              </div>
              <div className="mb-6 grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label
                    className="block mb-2 text-slate-800 font-medium"
                    htmlFor=""
                  >
                    Password
                  </label>
                  <input
                    className="appearance-none block w-full p-3 leading-5 text-slate-900 border border-coolGray-200 rounded-lg shadow-md placeholder-coolGray-400 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-opacity-50"
                    type="password"
                    placeholder="************"
                  />
                </div>
                <div>
                  <label
                    className="block mb-2 text-slate-800 font-medium"
                    htmlFor=""
                  >
                    Confirm Password
                  </label>
                  <input
                    className="appearance-none block w-full p-3 leading-5 text-slate-900 border border-coolGray-200 rounded-lg shadow-md placeholder-coolGray-400 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-opacity-50"
                    type="password"
                    placeholder="************"
                  />
                </div>
              </div>

              <a
                className="inline-block py-3 px-7 mb-6 w-full text-base text-green-50 font-medium text-center leading-6 bg-green-500 hover:bg-green-600 focus:ring-2 focus:ring-green-500 focus:ring-opacity-50 rounded-md shadow-sm"
                href="#"
              >
                Register
              </a>
              <p className="text-center">
                <span className="text-xs font-medium mr-2">
                  Already have an account?
                </span>
                <Link passHref href="/login">
                  <span className="cursor-pointer inline-block text-xs font-medium text-green-500 hover:text-green-600 hover:underline">
                    Login
                  </span>
                </Link>
              </p>
            </form>
          </div>
        </section>
      </main>

      <footer></footer>
    </div>
  );
};
export default Register;
